Vagrant.configure("2") do |config|
  config.vm.box = "jenkins"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"

    vb.cpus = "4"
  end
end
