- name: Install Jenkins
  import_role:
    name: galaxy.jenkins
  vars:
    jenkins_repo_url: 'deb https://pkg.jenkins.io/debian-stable binary/'
    jenkins_repo_key_url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
    jenkins_pkg_url: 'https://pkg.jenkins.io/debian-stable/binary'
    jenkins_version: '2.164.3'
    jenkins_admin_username: "{{ jenkins_credentials.admin_user }}"
    jenkins_admin_password: "{{ jenkins_credentials.admin_password }}"
    jenkins_plugins:
      - github
      - job-dsl
      - workflow-aggregator
      - pipeline-utility-steps
      - startup-trigger-plugin

- name: Install python dependencies
  pip:
    name:
      - python-jenkins
      - lxml
    state: present

- name: Initialize seed job
  jenkins_job:
    config: "{{ lookup('template', 'seed_job.xml.j2') }}"
    name: seed
    user: "{{ jenkins_credentials.admin_user }}"
    password: "{{ jenkins_credentials.admin_password }}"
  vars:
    repo_url: "{{ jenkins_seed_repo_url }}"
    job_dsl_targets: 'jenkins/job_dsl/**.groovy'

- name: Install docker
  import_role:
    name: galaxy.docker
  vars:
    docker_users:
      - jenkins
