- name: Install Jenkins
  import_role:
    name: galaxy.jenkins
  vars:
    jenkins_repo_url: 'deb https://pkg.jenkins.io/debian-stable binary/'
    jenkins_repo_key_url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
    jenkins_pkg_url: 'https://pkg.jenkins.io/debian-stable/binary'
    jenkins_version: '2.164.3'
    jenkins_plugins:
      - github
      - job-dsl
      - workflow-aggregator
      - pipeline-utility-steps
